name: run-cache
on:
  push:
    branches: [main]



jobs:
  build: 
    runs-on:  ubuntu-latest

    steps:
      - name: checkout home
      - uses: action/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: 14
      - run: npm ci 
      - run: npm test
        
